
check_mode: no

php_version: '8.1'
php_display_errors: "On"
php_date_timezone: "Europe/London"
php_enable_webserver: false


# apache_create_vhosts: false
# apache_remove_default_vhost: true
# apache_state: stopped

skip_roles: "{{ skip_roles }}"

profile: |
  lsb_release -d
  export WINHOME={{ lookup('env','WINHOME') }}
  export VAGRANT_WSL_ENABLE_WINDOWS_ACCESS="1"
  keychain $HOME/.ssh/id_rsa
  source $HOME/.keychain/{{ lookup('env','NAME') }}-sh

wsl_conf: |
  [automount]
  options="metadata,umask=0033"

gitconfig: |
  [user]
    name = jsherwin
    email = 1931307+very-random-man@users.noreply.github.com

  [core]
    autocrlf = true
    preloadindex = true
    fscache = true
    editor = vim

  [gc]
    auto = 256

  [pull]
    rebase = false
  [init]
    defaultBranch = main
