check_mode: no

php_version: '8.1'
php_display_errors: "On"
php_date_timezone: "Europe/London"
php_enable_webserver: false

skip_roles: "{{ skip_roles }}"

profile: |
  lsb_release -d
  export WINHOME={{ lookup('env','WINHOME') }}
  export VAGRANT_WSL_ENABLE_WINDOWS_ACCESS="1"
  keychain $HOME/.ssh/id_rsa
  source $HOME/.keychain/{{ lookup('env','NAME') }}-sh

bash: |
  if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w$(__git_ps1)\[\033[00m\]\$ '
  else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w$(__git_ps1)\$ '
  fi
  
  PROMPT_COMMAND="history -a; history -n"

wsl_conf: |
  [automount]
  options="metadata,umask=0033"

gitconfig: |

  [core]
    autocrlf = true
    preloadindex = true
    fscache = true
    editor = vim

  [gc]
    auto = 256

  [pull]
    rebase = false
  [init]
    defaultBranch = main